### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by TicklishGiraffe** [bigcoxinator/Lebanon-Township-Fire#1]
So I've only ever used github as a storage repository for python scripts.  Hows this shenanigans work? 
And if I were to clone it, how could I build it into website? <- What a noob

**Comment by bigcoxinator** [comment]
What do you mean by building it into a website?

**Comment by dpaolillo135** [comment]
I have to wonder..... are you in fact ticklish?

**Comment by TicklishGiraffe** [comment]
That will be up to your imagination Dannyboy!
And I mean like to look at it? I know nothing of html, so how to go from that to "Hey I can see what that website will look like if it went live right now!"

**Comment by bigcoxinator** [comment]
Download the zip and just tickle index.html

**Comment by TicklishGiraffe** [comment]
Hey it works! Thanks!
Ill just start reading the files and figure it out now.
Im going to break it so many ways just playing...
If I were to make something legit for this, how would I go about adding it and doing the whole git thing?

**Comment by TicklishGiraffe** [comment]
And please tell me tickle is the technical term for that

**Comment by bigcoxinator** [comment]
In order to add it, work on it by taking the files from the main branch, and create a new branch of the code. Under that new branch, you'll make all your changes and make sure to use the GitHub desktop app. There it will sync changes for you with the click of a button, and you can add descriptions to your changes. But do not edit the main branch. Once you're done with your changes in the branch you made, then we can go about getting it added into the main branch

**Comment by TicklishGiraffe** [comment]
Got it! Thanks!
